#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Software License Agreement (BSD)
#
# @author    Salman Omar Sohail <support@mybotshop.de>
# @copyright (c) 2025, MYBOTSHOP GmbH, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, is not permitted without the express permission
# of MYBOTSHOP GmbH.

import rclpy
from go2_zt30.libzt30 import ROS2ZT30Server

def launch_webserver(args=None):

    rclpy.init(args=args)
    
    ros2_zt30_server = ROS2ZT30Server()

    try:
        rclpy.spin(ros2_zt30_server)
    except KeyboardInterrupt:
        ros2_zt30_server.get_logger().info('Web server stopped by user.')
    finally:
        ros2_zt30_server.destroy_node()

if __name__ == '__main__':
    launch_webserver()
