#!/bin/sh

# Software License Agreement (BSD)
#
# @author    Salman Omar Sohail <support@mybotshop.de>
# @copyright (c) 2025, MYBOTSHOP GmbH, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, is not permitted without the express permission
# of MYBOTSHOP GmbH.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

REDDDD='\033[0;31m'
ORANGE='\033[0;33m'
DGREEN='\033[0;32m'
GREENN='\033[1;32m'
LGREEN='\033[0;32m'
WHITEE='\033[0;37m'
BLUEEE='\033[1;34m'
CYANNN='\033[0;96m'
YELLOW='\033[1;33m'
YEELOW='\033[0;93m'
PURPLE='\033[0;35m'
NCCCCC='\033[0m'

robot_status() {
    for service in $(systemctl list-units --type=service --all --no-legend \
                     | awk '{print $1}' \
                     | grep -E "^$1"); do
        if systemctl is-active --quiet "$service"; then
            printf "${YEELOW}Robot Service Status for ${CYANNN}%s:${DGREEN} Active ${NCCCCC}\n" "$service"
        else
            printf "${YEELOW}Robot Service Status for ${CYANNN}%s:${REDDDD} Not Active ${NCCCCC}\n" "$service"
        fi
    done
}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"       _  _  _  _  ____   __  ____  ____  _  _   __  ____                      "${WHITEE}
echo ${GREENN}"      ( \/ )( \/ )(  _ \ /  \(_  _)/ ___)/ )( \ /  \(  _ \                     "${WHITEE}
echo ${GREENN}"      / \/ \ )  /  ) _ ((  O ) )(  \___ \) __ ((  O )) __/                     "${WHITEE}
echo ${GREENN}"      \_)(_/(__/  (____/ \__/ (__) (____/\_)(_/ \__/(__)                       "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YEELOW}"GO2 MCU IP:      "${WHITEE}"        192.168.123.161                            "${WHITEE}
echo ${WHITEE}"                 "${WHITEE}"                                                   "${WHITEE}
echo ${YEELOW}"GO2 Nvidia IP:   "${WHITEE}"        192.168.123.18                             "${WHITEE}
echo ${YEELOW}"GO2 Web:         "${WHITEE}"        http://192.168.123.18:9000                 "${WHITEE}
echo ${YEELOW}"SSH:             "${WHITEE}"        ssh -X unitree@192.168.123.18              "${WHITEE}
echo ${YEELOW}"Pswd SSH:        "${WHITEE}"        123                                        "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"GO2 Drivers                                                                    "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
robot_status go2
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"Navigation                                                                     "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YEELOW}"GO2 Navi SLAM:       "${CYANNN}" ros2 launch go2_navigation slam.launch.py     "${WHITEE}
echo ${YEELOW}"GO2 Navi Odom:       "${CYANNN}" ros2 launch go2_navigation odom_navi.launch.py"${WHITEE}
echo ${YEELOW}"GO2 Navi Map:        "${CYANNN}" ros2 launch go2_navigation map_navi.launch.py "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"D1 Manipulator                                                                 "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YEELOW}"D1 Driver:           "${CYANNN}" ros2 launch d1_controller controller.launch.py"${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"Open Manipulator                                                               "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YEELOW}"OM Driver:           "${CYANNN}" ros2 launch go2_manipulation openmanipulator.launch.py"${WHITEE}
echo ${YEELOW}"OM Moveit:           "${CYANNN}" ros2 launch go2_manipulation moveit2.launch.py        "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"Auxiliary Sensors                                                              "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YEELOW}"Hesai:               "${CYANNN}" ros2 launch go2_lidars hesai.launch.py                "${WHITEE}
echo ${YEELOW}"Livox Mid360:        "${CYANNN}" ros2 launch go2_lidars livox_mid360.launch.py         "${WHITEE}
echo ${YEELOW}"OUSTER:              "${CYANNN}" ros2 launch go2_lidars ouster.launch.py               "${WHITEE}
echo ${YEELOW}"SIYI ZT30:           "${CYANNN}" ros2 launch go2_zt30 zt30.launch.py                   "${WHITEE}
echo ${YEELOW}"Realsense D435i:     "${CYANNN}" ros2 launch go2_depth_camera realsense_d435i.launch.py"${WHITEE}
echo ${YEELOW}"Realsense D405:      "${CYANNN}" ros2 launch go2_depth_camera realsense_d405.launch.py "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"Visualization & Control                                                        "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YEELOW}"GO2 Teleoperation:   "${CYANNN}" ros2 run teleop_twist_keyboard teleop_twist_keyboard"${WHITEE}
echo ${YEELOW}"GO2 Visualization:   "${CYANNN}" ros2 launch go2_viz view_robot.launch.py            "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YEELOW}"Rebuild package:     "${CYANNN}" colcon build --symlink-install                "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${PURPLEE}"https://www.docs.quadruped.de/projects/go2/html/index.html"${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}