/**:
  ros__parameters:
  # joy_teleop configuration
    deadzone: 0.1
    autorepeat_rate: 20.0
    # device_name: "Logitech Gamepad F710" # To get the device name: ros2 run joy joy_enumerate_devices 

  # teleop_twist_joy_node:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.4
      y: 0.4
    scale_linear_turbo:
      x: 1.0
      y: 1.0
    axis_angular:
      yaw: 2        # axe z (en verticale au dessus du robot)
    scale_angular:
      yaw: 0.6
    scale_angular_turbo:
      yaw: 1.2
    enable_button: 7
    enable_turbo_button: 9

  # twist_server_node:
    link_name: base_link
    robot: go2
    linear_scale: 0.5
    max_positive_linear_velocity: 0.5
    max_negative_linear_velocity: -0.5

  # twist_mux
    topics:

      logitech_joy:
        topic   : joy_teleop/cmd_vel
        timeout : 0.5
        priority: 25

      steamdeck_joy:
        topic   : steamdeck_joy_teleop/cmd_vel
        timeout : 0.5
        priority: 20

      web_joy:
        topic   : webserver/cmd_vel
        timeout : 0.5
        priority: 15

      interactive_marker:
        topic   : twist_marker_server/cmd_vel
        timeout : 0.5
        priority: 10      
      
      external:
        topic   : cmd_vel
        timeout : 0.5
        priority: 5

      autonomous_high_priority_cmd_vel:
        topic   : autonomous_high_priority/cmd_vel
        timeout : 0.5
        priority: 3

      autonomous_mid_priority_cmd_vel:
        topic   : autonomous_mid_priority/cmd_vel
        timeout : 0.5
        priority: 2

      autonomous_low_priority_cmd_vel:
        topic   : autonomous_low_priority/cmd_vel
        timeout : 0.5
        priority: 1

    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255


# Teleop configuration for wireless Gamepad using the x-pad configuration.
# Left thumb-stick up/down for velocity, left/right for twist
# RZ for enable
# R for enable-turbo
#
#         (LZ)                                 (RZ)
#         (L)                                  (R)
#       _=====_                               _=====_
#      / _____ \                             / _____ \
#    +.-'_____'-.---------------------------.-'_____'-.+
#   /   |     |  '.                       .'  |      |   \
#  / ___| /|\ |___ \   (-)         (+)   / ___| (Y)  |___ \
# / |      |      | ;                   ; |              | |
# | | <---   ---> | |                   | | (X)       (B)| |
# | |___   |   ___| ;                   ; |___       ____| /
# |\    | \|/ |    /  _     ___      _   \    | (A) |    /|
# | \   |_____|  .','" "', |___|  ,'" "', '.  |_____|  .' |
# |  '-.______.-' /       \ HOME /       \  '-._____.-'   |
# |               |   LJ  |------|   RJ  |                |
# |              /\       /      \       /\               |
# |             /  '.___.'        '.___.'  \              |
# |            /                            \             |
#  \          /                              \           /
#   \________/                                \_________/
#
# BUTTON         Value      GXTrust
#   A              0           0
#   B              1           1
#   X              2           3
#   Y              3           4
#   LZ                         8
#   RZ                         9
#   L                          6
#   R                          7
#   +                          11
#   -                          10
#   JoyLeft                    13
#   JoyRight                   14
#
#    AXIS        Value
# Left Horiz.      0      (-1 = vers la gauche)     {sur le robot l'axe horizontale est le y}
# Left Vert.       1      (-1 = vers le haut)
# Right Horiz.     2      ()
# Right Vert.      3
# Left Trigger     
# Right Trigger  

#   DPAD 0 value ( . ; . ) avec . = [-1;1]
# D-pad Horiz. gauche    (1,0)
# D-pad Horiz. gauche    (-1,0)     
# D-pad Vert. haut  (0,1)
# D-pad Vert. bas   (0,-1)