#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rclpy
from go2_host.libjoypy import Logitechf710Controls

def main(args=None):

    rclpy.init(args=args)

    jc = Logitechf710Controls()
    try:
        rclpy.spin(jc)
    except KeyboardInterrupt:
        pass
    finally:
        jc.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
	main()