#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Software License Agreement (BSD)
#
# @author    Salman Omar Sohail <support@mybotshop.de>
# @copyright (c) 2025, MYBOTSHOP GmbH, Inc., All rights reserved.
#

#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Redistribution and use in source and binary forms, with or without
# modification, is not permitted without the express permission
# of MYBOTSHOP GmbH.

import torch
import inflect
from TTS.api import TTS

device = "cuda" if torch.cuda.is_available() else "cpu"
tts = TTS(model_name='tts_models/en/jenny/jenny')


def mozilla_predefined_audio_generator():
    '''
    Dependencies via:
    sudo apt-get install espeak-ng
    pip install TTS 
    '''
    
    # tts.tts_to_file(text=f"Reactivating All Robot Services",
    #                 file_path="reactivation_all.mp3")
    # tts.tts_to_file(text=f"De activating All Robot Services",
    #                 file_path="deactivation_all.mp3")
    # tts.tts_to_file(text=f"Activating E Stop",
    #                 file_path="e_stop.mp3")
    # tts.tts_to_file(text=f"Releasing E Stop",
    #                 file_path="e_stop_release.mp3")
    # tts.tts_to_file(text=f"Recording RAWSS Robot Data",
    #                 file_path="record_rosbag.mp3")
    # tts.tts_to_file(text=f"Saving RAWSS Robot Data",
    #                 file_path="save_rosbag.mp3")    
    # tts.tts_to_file(text=f"Saving Robot System Logs",
    #                 file_path="create_logs.mp3")    
    # tts.tts_to_file(text=f"Rebooting Robot Computer",
    #                 file_path="reboot.mp3")
    # tts.tts_to_file(text=f"Reloading U dev rules",
    #                 file_path="udev.mp3")
    # tts.tts_to_file(text=f"Powhering off Robot Computer",
    #                 file_path="poweroff.mp3")
    # tts.tts_to_file(text=f"Restarting Network Manager",
    #                 file_path="re_network_manager.mp3")
    # tts.tts_to_file(text=f"Clearing Robot RAM",
    #                 file_path="clear_memory.mp3")
    tts.tts_to_file(text=f"Reactivating robot service",
                    file_path="reactivating_robot_service.mp3")
    tts.tts_to_file(text=f"De activating robot service",
                    file_path="deactivating_robot_service.mp3")

mozilla_predefined_audio_generator()