#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Software License Agreement (BSD)
#
# @author    Salman Omar Sohail <support@mybotshop.de>
# @copyright (c) 2024, MYBOTSHOP GmbH, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of MYBOTSHOP GmbH nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Redistribution and use in source and binary forms, with or without
# modification, is not permitted without the express permission
# of MYBOTSHOP GmbH.

import time
import rclpy
import numpy as np

from rclpy.node import Node
from go2_platform.utils.transforms import *
from tf2_ros import TransformBroadcaster
from math import sqrt, atan2, sin, cos, pi

from nav_msgs.msg import Odometry
from unitree_go.msg import SportModeState, LowState
from sensor_msgs.msg import JointState, Imu
from geometry_msgs.msg import Quaternion, Vector3, TransformStamped
from sensor_msgs.msg import BatteryState

class Go2StateController(Node):
    def __init__(self):
        super().__init__('go2_statepublisher')
        self.get_logger().info(f'{self.colorize("Initializing GO2 State Publisher","yellow")}')

        # Parameters
        self.declare_parameters(namespace='', parameters=[('robot_odom_pub',None),
                                                          ('robot_odom_tf',None),
                                                          ('robot_baselink_tf',None)])
        
        self.param_robot_odom_pub = self.get_parameter('robot_odom_pub').value
        self.param_robot_odom_tf = self.get_parameter('robot_odom_tf').value
        self.param_robot_baselink_tf = self.get_parameter('robot_baselink_tf').value
        
        self.get_logger().info(f'{self.colorize("robot_odom_pub:","blue")} {self.param_robot_odom_pub}')
        self.get_logger().info(f'{self.colorize("robot_odom_tf:","blue")} {self.param_robot_odom_tf}')
        self.get_logger().info(f'{self.colorize("robot_baselink_tf:","blue")} {self.param_robot_baselink_tf}')

        # Body dimensions
        self.bodyLength = 0.3762
        self.bodyWidth  = 0.0935

        # Leg dimensions
        self.l1 = 0
        self.l2 = 0.080 # hip
        self.l3 = 0.213 # thigh
        self.l4 = 0.213 # calf   

        # URDF
        self.robot_odom_tf     = self.param_robot_odom_tf
        self.robot_baselink_tf = self.param_robot_baselink_tf

        # Flags
        self.orientation_eu = 0 
        self.camera_data    = 0 
        self.foot_position  = 0
        self.foot_position_flag = False 
        self.go2_flag = False
        self.imu_state = None 
        self.odom_state = None 
        self.camera_state = None 
        self.go2_battery = None

        # Subscribers
        self.subscriber_state_contacts = self.create_subscription(SportModeState, 'sportmodestate', self.callback_state_contacts, 10)
        self.subscriber_lowstate = self.create_subscription(LowState, 'lf/lowstate', self.callback_lowstate, 10)
        self.subscriber_lidar_odom     = self.create_subscription(Odometry, 'utlidar/robot_odom', self.callback_lidar_odom, 10)

        # Publishers
        self.publisher_odom = self.create_publisher(Odometry, 'base/odom', 10)
        self.pub_data_odom = Odometry()

        self.publisher_odom_tf = TransformBroadcaster(self)
        self.pub_data_odom_tf = TransformStamped()

        self.publisher_imu = self.create_publisher(Imu, 'sensor/imu/data', 10)
        self.pub_data_imu = Imu()

        self.publisher_jointstate = self.create_publisher(JointState, 'platform/joint_states', 10)
        self.pub_data_jointstate = JointState()   
        
        self.publisher_battery = self.create_publisher(
            BatteryState, 'sensor/battery/state', 10)
        
        self.create_timer(0.01, self.update_joint_states)
        self.create_timer(0.01, self.update_imu)
        self.create_timer(0.01, self.update_odom)
        self.create_timer(2.0, self.update_battery_state)

        # Track Startup
        self.startup_time = time.time()
        self.startup_wait = 3.0

    def colorize(self, text, color):
        color_codes = {
            'green': '\033[92m',
            'yellow': '\033[93m',
            'orange': '\033[38;5;208m', 
            'blue': '\033[94m',
            'red': '\033[91m'
        }
        return color_codes[color] + text + '\033[0m'

    def callback_lowstate(self, data):
        self.go2_battery = data.bms_state
        self.go2_motor_state = data.motor_state
        self.go2_flag = True
        
    def callback_state_contacts(self, data):
        self.imu_state = data.imu_state
        self.robot_height = data.body_height
        self.foot_position = data.foot_position_body
        self.foot_position_flag = True
    
    def callback_lidar_odom(self, data):
        self.odom_state = data

    def update_odom(self):
        if self.odom_state is not None:
            self.pub_data_odom.header.stamp = self.get_clock().now().to_msg()
            self.pub_data_odom.header.frame_id = self.robot_odom_tf
            self.pub_data_odom.child_frame_id = self.robot_baselink_tf  
            self.pub_data_odom.pose.pose.position.x = self.odom_state.pose.pose.position.x 
            self.pub_data_odom.pose.pose.position.y = self.odom_state.pose.pose.position.y  
            self.pub_data_odom.pose.pose.position.z = self.odom_state.pose.pose.position.z 
            self.pub_data_odom.pose.pose.orientation = self.odom_state.pose.pose.orientation
            self.pub_data_odom.twist  = self.odom_state.twist
            self.publisher_odom.publish(self.pub_data_odom)

            self.pub_data_odom_tf.header.frame_id = self.robot_odom_tf
            self.pub_data_odom_tf.child_frame_id = self.robot_baselink_tf
            self.pub_data_odom_tf.header.stamp = self.get_clock().now().to_msg()
            self.pub_data_odom_tf.transform.translation.x = self.pub_data_odom.pose.pose.position.x
            self.pub_data_odom_tf.transform.translation.y = self.pub_data_odom.pose.pose.position.y
            self.pub_data_odom_tf.transform.translation.z = self.pub_data_odom.pose.pose.position.z
            self.pub_data_odom_tf.transform.rotation = self.pub_data_odom.pose.pose.orientation
            if self.param_robot_odom_pub:
                self.publisher_odom_tf.sendTransform(self.pub_data_odom_tf)
            self.get_logger().info(f'{self.colorize("GO2 Odom Data Received","green")}', once=True)
        else:
            if time.time() - self.startup_time > self.startup_wait:
                self.get_logger().error(f'{self.colorize("No GO2 Odom Data Received","orange")}', throttle_duration_sec=5)

    def update_imu(self):
        if self.imu_state is not None:
            self.pub_data_imu.orientation =  Quaternion(x=float(self.imu_state.quaternion[0]),
                                                        y=float(self.imu_state.quaternion[1]),
                                                        z=float(self.imu_state.quaternion[2]),
                                                        w=float(self.imu_state.quaternion[3]))
            self.pub_data_imu.angular_velocity = Vector3(
                x=float(self.imu_state.gyroscope[0]),
                y=float(self.imu_state.gyroscope[1]),
                z=float(self.imu_state.gyroscope[2])
            )
            self.pub_data_imu.linear_acceleration = Vector3(
                x=float(self.imu_state.accelerometer[0]),
                y=float(self.imu_state.accelerometer[1]),
                z=float(self.imu_state.accelerometer[2])
            )
            self.publisher_imu.publish(self.pub_data_imu)
            self.get_logger().info(f'{self.colorize("GO2 IMU Data Received","green")}', once=True)
        else:
            if time.time() - self.startup_time > self.startup_wait:
                self.get_logger().error(f'{self.colorize("No GO2 IMU Data Received","orange")}', throttle_duration_sec=5)

    def update_joint_states(self):
        self.pub_data_jointstate.header.stamp = self.get_clock().now().to_msg()
        self.pub_data_jointstate.header.frame_id = 'base_link'
        self.pub_data_jointstate.name = [
            'FR_thigh_joint', 'FR_hip_joint', 'FR_calf_joint',
            'FL_thigh_joint', 'FL_hip_joint', 'FL_calf_joint',
            'RR_thigh_joint', 'RR_hip_joint', 'RR_calf_joint',
            'RL_thigh_joint', 'RL_hip_joint', 'RL_calf_joint',
            'FR_wheel_joint', 'FL_wheel_joint', 'RR_wheel_joint', 'RL_wheel_joint']
        self.pub_data_jointstate.effort = [0.0]*19

        if self.go2_flag == False:
            if time.time() - self.startup_time > self.startup_wait:
                self.get_logger().error(
                    f'{self.colorize("No GO2 joint positions Data Received","orange")}', throttle_duration_sec=5)
            self.pub_data_jointstate.position = [0.0]*19
            return
        else:
            self.joints_assignment()
            self.get_logger().info(
                f'{self.colorize("GO2 joint positions Data Received","green")}', once=True)
            self.publisher_jointstate.publish(self.pub_data_jointstate)

    def joints_assignment(self):
        """
        Assigns the joint positions to the JointState message.
        """
        joint_indices = {
            "FR_thigh_joint": 1,
            "FR_hip_joint": 0,
            "FR_calf_joint": 2,
            "FL_thigh_joint": 4,
            "FL_hip_joint": 3,
            "FL_calf_joint": 5,
            "RR_thigh_joint": 7,
            "RR_hip_joint": 6,
            "RR_calf_joint": 8,
            "RL_thigh_joint": 10,
            "RL_hip_joint": 9,
            "RL_calf_joint": 11,
            "FR_wheel_joint": 12,
            "FL_wheel_joint": 13,
            "RR_wheel_joint": 14,
            "RL_wheel_joint": 15,
        }

        joint_positions = [
            self.go2_motor_state[index].q for index in joint_indices.values()]

        self.pub_data_jointstate.position = joint_positions
    
    def update_battery_state(self):
        try:
            if not self.go2_battery:
                return

            self.get_logger().info(
                f'{self.colorize(f"GO2 Battery Publisher Activated","green")}', once=True)

            msg = BatteryState()
            msg.header.stamp = self.get_clock().now().to_msg()

            # Estimate voltage
            voltage = self.go2_battery.cell_vol

            voltages = [v / 1000.0 for v in voltage if v > 0]
            msg.voltage = sum(voltages)

            # Convert current from mA to A
            msg.current = self.go2_battery.current / 1000.0

            # Estimate percentage from SoC
            msg.percentage = self.go2_battery.soc / 100.0
            msg.charge = msg.percentage * msg.voltage

            msg.power_supply_status = BatteryState.POWER_SUPPLY_STATUS_DISCHARGING
            msg.power_supply_health = BatteryState.POWER_SUPPLY_HEALTH_GOOD
            msg.power_supply_technology = BatteryState.POWER_SUPPLY_TECHNOLOGY_LION
            msg.present = True

            self.publisher_battery.publish(msg)

        except Exception as e:
            self.get_logger().error(f"Exception in update_battery_state: {e}")

    def destroy_node(self):
        self.get_logger().info(f'{self.colorize("GO2 State Publisher is shutting down","red")}')
        super().destroy_node() 

def main(args=None):

    rclpy.init(args=args)
    rk = Go2StateController()

    try:
        rclpy.spin(rk)
    except KeyboardInterrupt:
        pass
    finally:
        rk.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()